Create user entity
hack4impact-mcgill/MADA-v2 pull request #24
Opened 2022-10-24 23:11 UTC by lilygostovic

2022-10-24 23:20 UTC, mkramarz requested changes, later dismissed
Really good! Two small requests:
- Move the file into its own folder under `backend/src/entities/`
- Rename the file and class to "UserEntity"

2022-10-24 23:39 UTC, peterghrong requested changes
Need Migration plan, code looks good aside from minor change
https://orkhan.gitbook.io/typeorm/docs/migrations

2022-10-24 23:39 UTC, peterghrong commented on backend/src/entities/UserEntity.ts
> +  email: string;
Either email or Username might have to be unique?
Prob check with @kehwhy @cdjamalov

2022-10-31 22:42 UTC, peterghrong approved these changes
![image](https://user-images.githubusercontent.com/66083521/199123675-d5061269-9480-4ef1-9e11-a0f4cf930f39.png)

2022-10-31 22:43 UTC, merged